# Generated by Django 4.2.1 on 2023-07-07 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recruiters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selected',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='selected',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected', to='recruiters.job'),
        ),
    ]
