# Generated by Django 4.2.1 on 2023-07-29 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0003_savedjobs'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='savedjobs',
            constraint=models.UniqueConstraint(fields=('user', 'job'), name='unique_saved_jobs'),
        ),
    ]
